# Generated by Django 4.1.4 on 2022-12-11 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('title', models.CharField(default='project title', max_length=250)),
                ('description', models.TextField(default='Another project')),
                ('tags', models.CharField(default='html, css, django', max_length=250)),
                ('link', models.URLField(default='https://github.com/maby200/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
